@PORT = 5000
@RootURL = http://localhost:{{PORT}}/api/v1

@userEP = {{RootURL}}/users

###

POST {{userEP}}/signup
Content-Type: application/json

{
    "username":"Ram",
    "email":"email",
    "password":"password"
}

###
POST  {{userEP}}/login
Content-Type: application/json

{
    "email":"email",
    "password":"password"
}
