@PORT = 5000
@rootURL = http://localhost:{{PORT}}/api/v1

@userEP = {{rootURL}}/users

@transactionEP = {{rootURL}}/transaction

###

POST {{userEP}}/signup
Content-Type: application/json

{
    "username":"Ram",
    "email":"email",
    "password":"password"
}

###
POST  {{userEP}}/login
Content-Type: application/json

{
    "email":"shubik@gmail.com",
    "password":"password"
}

###

POST {{transactionEP}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNodWJpa0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc0MjA5NDEsImV4cCI6MTczNzUwNzM0MX0.OU9NC2f-0V2_Ax9sUk4Yp-30TY3L_0sn7iTVHAt2k7Y

{
    "type":"income",
    "amount":10000,
    "description":"Salary",
    "date":"01-21-2025"
}
###
GET {{transactionEP}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNodWJpa0BnbWFpbC5jb20iLCJpYXQiOjE3Mzc0MjA5NDEsImV4cCI6MTczNzUwNzM0MX0.OU9NC2f-0V2_Ax9sUk4Yp-30TY3L_0sn7iTVHAt2k7Y
