@PORT = 5000
@userEP = http://localhost:{{PORT}}/api/v1/users


###
# Signup API

POST {{userEP}}/signup
Content-Type: application/json

{
    "username":"jack",
    "email":"jack@gmail.com",
    "password":"password"
}

###
#Login API
POST  {{userEP}}/login
Content-Type: application/json

{
    "email":"shubik@gmail.com",
    "password":"password"
}
